spring.application.name=llm-process-automation-prototype
spring.config.import=optional:file:.env[.properties]
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG
spring.ai.openai.api-key=${OPENAI_API_KEY}
app.chat.log-advisor.enabled=false
