spring.application.name=llm-process-automation-prototype
spring.config.import=optional:file:.env[.properties]
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG
spring.ai.openai.api-key=${OPENAI_API_KEY}
app.chat.log-advisor.enabled=true

app.llm.rate-limiter.enabled=true
app.llm.rate-limiter.min-delay-ms=500
app.llm.rate-limiter.retry-max-attempts=3
app.llm.rate-limiter.retry-initial-delay-ms=10000
app.llm.rate-limiter.retry-multiplier=2.0
